replicaCount: 3

image:
  repository:
  tag:
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: cfcr

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/force-hsts: "true"
    ingress.kubernetes.io/hsts-max-age: "315360000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-preload: "true"
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
    ingress.kubernetes.io/custom-frame-options-value: "SAMEORIGIN"
    ingress.kubernetes.io/referrer-policy: "no-referrer-when-downgrade"
    ingress.kubernetes.io/content-security-policy: "upgrade-insecure-requests"
    ingress.kubernetes.io/custom-response-headers: |
      Feature-Policy: geolocation none; midi none; notifications none; push none; sync-xhr none; microphone none; camera none; magnetometer none; gyroscope none; speaker self; vibrate none; fullscreen self; payment none; ||
  hosts:
    - host: www.readinglevel.app
      paths:
        - /

resources:
  requests:
    cpu: 10m
    memory: 10Mi
  limits:
    cpu: 10m
    memory: 10Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - readinglevel
        topologyKey: "kubernetes.io/hostname"
