name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: asdf_install
        uses: asdf-vm/actions/install@v1.0.1
        env:
          NODEJS_CHECK_SIGNATURES: 'no'
      - env:
          AWS_DEFAULT_REGION: 'us-west-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        working-directory: ./deployment
        run: |
          npm ci
          pulumi preview --diff -s readinglevel
